### ISSUE TITLE
Using errors_ts in aurelia is not possible

### ISSUE THREAD

**Issue by Vyperus** [essential-projects/errors_ts#16]
#### Describe your issue

Using errors_ts in bpmn-studio (or any aurelia-app) leads to this Errors:
<img width="1427" alt="bildschirmfoto 2018-07-02 um 17 08 45" src="https://user-images.githubusercontent.com/17248802/42171850-ad63cbc8-7e1a-11e8-9c05-49e4e15cd600.png">
<img width="890" alt="bildschirmfoto 2018-07-02 um 17 09 34" src="https://user-images.githubusercontent.com/17248802/42171868-b9a83090-7e1a-11e8-9cd5-dc5cc7886068.png">

This counts for modules that are used inside the aurelia-app as well.
For example: Using the SolutionExplorerService, which is using the errors_ts, in an aurelia-app is not possible.

#### How can others reproduce the issue?

1) Create a new aurelia-app with `au new`. (Dont use webpack)
2) `npm link @essential-projects/errors_ts` from this branch: https://github.com/essential-projects/errors_ts/tree/feature/erase_logger
3) Add 
```
          {
            "name": "@essential-projects/errors_ts",
            "main": "index.js",
            "path": "../node_modules/@essential-projects/errors_ts/dist/amd"
          }
```
to your aurelia.json.
4) Open a file and `throw new BadRequestError('test')`.
5) `au run`
6) Open the app in Chrome.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by 5ebastianMeier** [comment]
Fixed in https://github.com/essential-projects/errors_ts/pull/17
