### ISSUE TITLE
✨ Error with code 419 is missing

### ISSUE THREAD

**Issue by heikomat** [essential-projects/errors_ts#2]
#### Describe your issue

HTTP-Statuscode 419 is [Authentication Timeout](http://getstatuscode.com/419), and it is missing

#### How can others reproduce the issue?

An `AuthenticationTimeoutError` can't be used

#### Possible solution

Add a `AuthenticationTimeoutError`-class

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/72
